<?php

namespace Modules\Core\Support\Automation;

class UpstreamPullRequestPayloadBuilder
{
    /**
     * @param array{
     *   track: string,
     *   upstream_ref: string,
     *   upstream_sha: string,
     *   replay_branch: string,
     *   verification_profile: string,
     *   verification_status?: string,
     *   patch_commit_count?: int
     * } $report
     * @return array{title: string, body: string, head: string, base: string, draft: bool}|null
     */
    public function build(UpstreamTrackConfig $track, array $report): ?array
    {
        if (! $track->openPr || $track->prBaseBranch === null) {
            return null;
        }

        return [
            'title' => sprintf(
                '[automation] Replay %s onto %s (%s)',
                $track->name,
                $track->upstreamRef,
                substr($report['upstream_sha'], 0, 12),
            ),
            'body' => implode("\n", [
                '## Upstream Replay Summary',
                '',
                sprintf('- Track: `%s`', $track->name),
                sprintf('- Upstream ref: `%s`', $track->upstreamRef),
                sprintf('- Upstream SHA: `%s`', $report['upstream_sha']),
                sprintf('- Replay branch: `%s`', $track->replayBranch),
                sprintf('- Verification profile: `%s`', $track->verificationProfile),
                sprintf('- Patch commits: `%d`', (int) ($report['patch_commit_count'] ?? 0)),
                sprintf('- Verification status: `%s`', $report['verification_status'] ?? 'pending'),
                '',
                'This PR was generated by the modular upstream replay workflow.',
            ]),
            'head' => $track->replayBranch,
            'base' => $track->prBaseBranch,
            'draft' => true,
        ];
    }
}
